### PR TITLE
Fixed build error with gpu_people DataSynth

### PR DESCRIPTION
**Pull request by amuetzel**
The DataSynth directory didn't include the FindEigen.cmake module, resulting in a build failure on my ArchLinux box if -DCMAKE_MODULE_PATH=/path/to/pcl/cmake/Modules isn't passed to cmake. With this commit, this isn't necessary any more. 
(Please disregard this pull request if the original behaviour is intended.)

### CODE REVIEW

**Comment by taketwo** [comment]
Is this the same module as in the main repository?

**Comment by amuetzel** [comment]
Ah, no. Sorry, copied one from the wrong place. Should I replace it by the PCL one and open a new pull request?

**Comment by taketwo** [comment]
I'm not sure if it is that important, but for the sake of consistency I would prefer the same module in both repositories. You may simply update this pull request.

**Comment by amuetzel** [comment]
Your are right. For cleanliness, I didn't want to remove the old cmake file and commit the new one again, so I created https://github.com/PointCloudLibrary/data/pull/7 with the correct file.

**Pull request closed without merging**
