### PR TITLE
adding terrain data from ISPRS study

### PR DESCRIPTION
**Pull request by chambbj**

### CODE REVIEW

**Comment by chambbj** [comment]
@jspricke @rbrusu Didn't know if either of you had seen this or given much thought to it. It's data from a study back in 2003 (http://www.itc.nl/isprswgIII-3/filtertest/) that can be used to evaluate ground finding algorithms. I will likely write up a tutorial or two for my recent contributions to PCL that will reference these data sets.

**Comment by rbrusu** [comment]
looks interesting, thanks for the heads up.

**Comment by jspricke** [comment]
@rbrusu If you don't object, I will merge this next week.

**Comment by rbrusu** [comment]
Looks good!

**Pull request merged**
